# Dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Відкриває порт 5000
EXPOSE 5000

# Запускає сервер
CMD ["python", "main.py"]